# -*- coding: utf-8 -*-
"""data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITKG9DcnaOehP-MYwCUS4yfuux0x2tqr
"""

import nltk
nltk.download('punkt_tab')
import re
import re
import nltk
from nltk.tokenize import sent_tokenize

nltk.download("punkt")

DOCUMENT1 = "Operating the Climate Control System  Your Googlecar has a climate control system that allows you to adjust the temperature and airflow in the car. To operate the climate control system, use the buttons and knobs located on the center console.  Temperature: The temperature knob controls the temperature inside the car. Turn the knob clockwise to increase the temperature or counterclockwise to decrease the temperature. Airflow: The airflow knob controls the amount of airflow inside the car. Turn the knob clockwise to increase the airflow or counterclockwise to decrease the airflow. Fan speed: The fan speed knob controls the speed of the fan. Turn the knob clockwise to increase the fan speed or counterclockwise to decrease the fan speed. Mode: The mode button allows you to select the desired mode. The available modes are: Auto: The car will automatically adjust the temperature and airflow to maintain a comfortable level. Cool: The car will blow cool air into the car. Heat: The car will blow warm air into the car. Defrost: The car will blow warm air onto the windshield to defrost it."
DOCUMENT2 = 'Your Googlecar has a large touchscreen display that provides access to a variety of features, including navigation, entertainment, and climate control. To use the touchscreen display, simply touch the desired icon.  For example, you can touch the "Navigation" icon to get directions to your destination or touch the "Music" icon to play your favorite songs.'
DOCUMENT3 = "Shifting Gears Your Googlecar has an automatic transmission. To shift gears, simply move the shift lever to the desired position.  Park: This position is used when you are parked. The wheels are locked and the car cannot move. Reverse: This position is used to back up. Neutral: This position is used when you are stopped at a light or in traffic. The car is not in gear and will not move unless you press the gas pedal. Drive: This position is used to drive forward. Low: This position is used for driving in snow or other slippery conditions."

documents = [DOCUMENT1, DOCUMENT2, DOCUMENT3]

paragraphs = documents.copy()

import re
import nltk
from nltk.tokenize import sent_tokenize

nltk.download("punkt", quiet=True) # Download punkt only if not already downloaded

def preprocess_text(text):
    """Remove extra whitespaces and normalize text."""
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def chunk_text(text, chunk_size=200):
    """Split text into chunks of ~200 words while preserving sentence boundaries."""
    sentences = sent_tokenize(text)  # Split text into sentences
    chunks = []
    current_chunk = []
    current_length = 0

    for sentence in sentences:
        sentence_length = len(sentence.split())
        if current_length + sentence_length > chunk_size:
            chunks.append(" ".join(current_chunk))
            current_chunk = []
            current_length = 0

        current_chunk.append(sentence)
        current_length += sentence_length

    if current_chunk:
        chunks.append(" ".join(current_chunk))  # Append last chunk

    return chunks

# Your list of paragraphs (replace with your actual paragraphs)


# Process each paragraph
processed_chunks = []
for paragraph in paragraphs:
    preprocessed_paragraph = preprocess_text(paragraph)
    chunks = chunk_text(preprocessed_paragraph)
    processed_chunks.extend(chunks) # Add the chunks to the list

# Now processed_chunks contains all the chunks from all paragraphs
for i, chunk in enumerate(processed_chunks):
    print(f"Chunk {i+1}:\n{chunk}\n")  # Print each chunk
    print("-" * 20) # Separator

